# Generated by Django 6.0.2 on 2026-02-28 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("control", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_user_id", models.CharField(max_length=128)),
                ("username", models.CharField(blank=True, max_length=128)),
                ("display_name", models.CharField(blank=True, max_length=128)),
                ("is_allowed", models.BooleanField(default=True)),
                ("role_hint", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Transport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                (
                    "mode",
                    models.CharField(
                        choices=[("polling", "Polling"), ("webhook", "Webhook"), ("both", "Both")],
                        default="polling",
                        max_length=16,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CommsConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_conversation_id", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "control_conversation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comms_conversation",
                        to="control.controlconversation",
                    ),
                ),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="comms.transport",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("transport", "external_conversation_id")},
            },
        ),
        migrations.CreateModel(
            name="CommsMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("external_message_id", models.CharField(blank=True, max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Incoming"), ("out", "Outgoing")],
                        default="in",
                        max_length=8,
                    ),
                ),
                ("text", models.TextField()),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="comms.commsconversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="comms.externalidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="externalidentity",
            name="transport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identities",
                to="comms.transport",
            ),
        ),
        migrations.CreateModel(
            name="TransportEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("bot", "Bot"), ("webhook", "Webhook")], max_length=16
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                (
                    "transport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="comms.transport",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="externalidentity",
            unique_together={("transport", "external_user_id")},
        ),
    ]
