# Generated by Django 6.0.2 on 2026-02-28 23:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_default_conversation'),
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commsconversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commsconversation',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='comms.transportendpoint'),
        ),
        migrations.AlterUniqueTogether(
            name='commsconversation',
            unique_together={('endpoint', 'external_conversation_id')},
        ),
        migrations.CreateModel(
            name='PendingPairing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pair_code', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('claimed_chat_id', models.CharField(blank=True, max_length=64, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_pairings', to='agents.agent')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='comms.transportendpoint')),
            ],
            options={
                'indexes': [models.Index(fields=['endpoint', 'pair_code'], name='comms_pendi_endpoin_43e9c5_idx'), models.Index(fields=['status', 'expires_at'], name='comms_pendi_status_ad8874_idx')],
            },
        ),
    ]
