# Generated by Django 6.0.2 on 2026-03-12 15:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_populate_endpoint'),
        ('core', '0002_useractionlog'),
        ('runs', '0007_rename_runs_runarchive_run_created_at_idx_runs_runarc_run_id_687157_idx_and_more'),
        ('tools', '0007_rename_tools_toola_run_id_97a44f_idx_tools_toola_run_id_ccf71c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteApprovalTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_chat_id', models.CharField(max_length=255)),
                ('external_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('short_code', models.CharField(max_length=8)),
                ('callback_token', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='pending', max_length=16)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('scope_options_snapshot', models.JSONField(blank=True, default=list)),
                ('web_url', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField()),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by_external_user_id', models.CharField(blank=True, default='', max_length=128)),
                ('acted_by_label', models.CharField(blank=True, default='', max_length=128)),
                ('action_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_approval_tickets', to='comms.commsconversation')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_approval_tickets', to='comms.transportendpoint')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_approval_tickets', to='runs.agentrun')),
                ('tool_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_approval_tickets', to='tools.toolcall')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_approval_tickets', to='comms.transport')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_approval_tickets', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'status', 'expires_at'], name='comms_remot_convers_2f19d8_idx'), models.Index(fields=['endpoint', 'status', 'expires_at'], name='comms_remot_endpoin_3ad20b_idx'), models.Index(fields=['tool_call', 'status'], name='comms_remot_tool_ca_d4a174_idx'), models.Index(fields=['callback_token'], name='comms_remot_callbac_8f17f3_idx')],
            },
        ),
    ]
