# Generated by Django 4.2.28 on 2026-02-23 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('default_model', models.CharField(default='gpt-5', max_length=80)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=4)),
                ('system_prompt', models.TextField()),
                ('plan_enabled', models.BooleanField(default=False)),
                ('tool_policy_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'name'], name='agents_agen_workspa_d55b1d_idx'), models.Index(fields=['workspace', 'created_at'], name='agents_agen_workspa_f2e56a_idx')],
                'unique_together': {('workspace', 'name')},
            },
        ),
    ]
