# Generated by Django 4.2.28 on 2026-02-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="policy_name",
            field=models.CharField(default="react", max_length=32),
        ),
    ]
