# Generated by Django 6.0.2 on 2026-02-28 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_policy_name'),
        ('control', '0003_ingestevent_resultmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='default_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_agents', to='control.controlconversation'),
        ),
    ]
