# Generated by Django 6.0.2 on 2026-03-01 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_owner_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agent',
            new_name='agents_agen_owner_i_1312f7_idx',
            old_name='agents_agent_owner_created_idx',
        ),
    ]
