# Generated by Django 6.0.2 on 2026-03-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_rename_agents_agent_owner_created_idx_agents_agen_owner_i_1312f7_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='sandbox_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
