# Generated by Django 6.0.2 on 2026-03-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0008_agent_soul_blank"),
        ("agents", "0008_alter_agent_soul"),
    ]

    operations = []
