# Generated by Django 6.0.2 on 2026-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0011_add_role_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="default_model",
            field=models.CharField(
                choices=[
                    ("gpt-5", "gpt-5"),
                    ("gpt-5-mini", "gpt-5-mini"),
                    ("gpt-5-nano", "gpt-5-nano"),
                    ("gpt-5-reasoning", "gpt-5-reasoning"),
                    ("gpt-5-reasoning-mini", "gpt-5-reasoning-mini"),
                    ("gpt-5-code", "gpt-5-code"),
                    ("gpt-4.1", "gpt-4.1"),
                    ("gpt-4.1-mini", "gpt-4.1-mini"),
                    ("gpt-4.1-nano", "gpt-4.1-nano"),
                ],
                default="gpt-5",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="agent",
            name="role",
            field=models.CharField(
                choices=[
                    ("coding", "Coding"),
                    ("writing", "Writing"),
                    ("researching", "Researching"),
                    ("planning", "Planning"),
                    ("assisting", "Assisting"),
                ],
                default="assisting",
                max_length=32,
            ),
        ),
    ]
