# Generated by Django 6.0.2 on 2026-03-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0012_alter_agent_default_model_alter_agent_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="default_model",
            field=models.CharField(default="gpt-5", max_length=32),
        ),
    ]
