# Generated by Django 4.2.28 on 2026-02-23 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('WAITING_FOR_APPROVAL', 'Waiting for Approval'), ('WAITING_FOR_TOOL', 'Waiting for Tool'), ('WAITING_FOR_SUBRUN', 'Waiting for Subrun'), ('WAITING_FOR_USER', 'Waiting for User'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=24)),
                ('channel', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('TELEGRAM', 'Telegram'), ('API', 'API')], db_index=True, default='DASHBOARD', max_length=12)),
                ('input_text', models.TextField(blank=True, default='')),
                ('final_text', models.TextField(blank=True, default='')),
                ('current_step_index', models.IntegerField(default=0)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('max_steps', models.IntegerField(default=80)),
                ('max_tool_calls', models.IntegerField(default=40)),
                ('locked_by', models.CharField(blank=True, default='', max_length=120)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='agents.agent')),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_runs', to='runs.agentrun')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs_started', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FILE', 'File'), ('TEXT', 'Text'), ('IMAGE', 'Image'), ('JSON', 'JSON'), ('REPORT', 'Report')], default='FILE', max_length=12)),
                ('name', models.CharField(blank=True, default='', max_length=180)),
                ('mime_type', models.CharField(blank=True, default='', max_length=120)),
                ('storage_path', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='runs.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.IntegerField()),
                ('kind', models.CharField(choices=[('PLAN', 'Plan'), ('MODEL_CALL', 'Model Call'), ('TOOL_CALL', 'Tool Call'), ('OBSERVATION', 'Observation'), ('MESSAGE', 'Message'), ('SPAWN_SUBRUN', 'Spawn Subrun')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='runs.agentrun')),
            ],
        ),
        migrations.CreateModel(
            name='RunEvent',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='runs.agentrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'seq'], name='runs_runeve_run_id_0e30da_idx'), models.Index(fields=['run', 'created_at'], name='runs_runeve_run_id_ee0fc6_idx'), models.Index(fields=['event_type', 'created_at'], name='runs_runeve_event_t_0504d9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='runevent',
            constraint=models.UniqueConstraint(fields=('run', 'seq'), name='uniq_event_seq_per_run'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['run', 'type', 'created_at'], name='runs_artifa_run_id_b50dca_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'step_index'], name='runs_agents_run_id_d9a0ba_idx'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['run', 'kind', 'created_at'], name='runs_agents_run_id_764df1_idx'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'step_index'), name='uniq_step_index_per_run'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['workspace', 'status', 'started_at'], name='runs_agentr_workspa_5652ba_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['agent', 'started_at'], name='runs_agentr_agent_i_074e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['parent_run', 'created_at'], name='runs_agentr_parent__6102f6_idx'),
        ),
    ]
