# Generated by Django 4.2.28 on 2026-02-24 09:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0002_add_locked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("PAUSED", "Paused"),
                    ("WAITING_FOR_APPROVAL", "Waiting for Approval"),
                    ("WAITING_FOR_TOOL", "Waiting for Tool"),
                    ("WAITING_FOR_SUBRUN", "Waiting for Subrun"),
                    ("WAITING_FOR_USER", "Waiting for User"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="agentstep",
            name="kind",
            field=models.CharField(
                choices=[
                    ("PLAN", "Plan"),
                    ("MODEL_CALL", "Model Call"),
                    ("TOOL_CALL", "Tool Call"),
                    ("SUBRUN_SPAWN", "Subrun Spawn"),
                    ("ACTION", "Action"),
                    ("FINAL", "Final"),
                    ("OBSERVATION", "Observation"),
                    ("MESSAGE", "Message"),
                    ("SPAWN_SUBRUN", "Spawn Subrun"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="SubrunLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("group_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                (
                    "join_policy",
                    models.CharField(
                        choices=[
                            ("WAIT_ALL", "Wait for all subruns"),
                            ("WAIT_ANY", "Resume after any child completes"),
                            ("QUORUM", "Resume after quorum"),
                            ("TIMEOUT", "Resume on timeout"),
                        ],
                        default="WAIT_ALL",
                        max_length=16,
                    ),
                ),
                ("quorum", models.PositiveIntegerField(blank=True, null=True)),
                ("timeout_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "failure_policy",
                    models.CharField(
                        choices=[
                            ("FAIL_FAST", "Fail parent on child failure"),
                            ("IGNORE_FAILURE", "Ignore child failures"),
                            ("CANCEL_SIBLINGS", "Cancel siblings on failure"),
                        ],
                        default="FAIL_FAST",
                        max_length=32,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "child_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subrun_link",
                        to="runs.agentrun",
                    ),
                ),
                (
                    "parent_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subrun_links",
                        to="runs.agentrun",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["parent_run", "group_id"], name="runs_subrun_parent__f1e225_idx"
                    ),
                    models.Index(
                        fields=["parent_run", "child_run"], name="runs_subrun_parent__e85061_idx"
                    ),
                ],
            },
        ),
    ]
