# Generated by Django 4.2.28 on 2026-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0003_alter_agentrun_status_alter_agentstep_kind_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="current_task_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
