# Generated by Django 4.2.28 on 2026-02-24 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0004_agentrun_current_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentrun",
            name="correlation_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="agentstep",
            name="correlation_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="runevent",
            name="correlation_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddIndex(
            model_name="agentstep",
            index=models.Index(
                fields=["run", "correlation_id"], name="runs_agents_run_id_4f08b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runevent",
            index=models.Index(
                fields=["run", "correlation_id"], name="runs_runeve_run_id_3d3d18_idx"
            ),
        ),
    ]
