# Generated by Django 6.0.2 on 2026-02-28 15:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0006_run_archive"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="runarchive",
            new_name="runs_runarc_run_id_687157_idx",
            old_name="runs_runarchive_run_created_at_idx",
        ),
        migrations.AlterField(
            model_name="runarchive",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="runarchive",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="runarchive",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
