# Generated by Django 6.0.2 on 2026-03-13 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0008_agentrun_previous_response_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('objective', models.TextField(blank=True, default='')),
                ('current_plan', models.TextField(blank=True, default='')),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('recent_tool_results', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='runs.agentrun')),
            ],
            options={
                'indexes': [models.Index(fields=['updated_at'], name='runs_runmem_updated_9018a4_idx')],
            },
        ),
    ]
