# Generated by Django 6.0.2 on 2026-03-15 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agent_default_model'),
        ('core', '0002_useractionlog'),
        ('runs', '0009_runmemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='delivery_target',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='execution_mode',
            field=models.CharField(choices=[('interactive', 'Interactive'), ('headless', 'Headless')], db_index=True, default='interactive', max_length=24),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='trigger_kind',
            field=models.CharField(choices=[('user_chat', 'User Chat'), ('scheduled_task', 'Scheduled Task'), ('system', 'System')], db_index=True, default='user_chat', max_length=24),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='trigger_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['execution_mode', 'trigger_kind', 'started_at'], name='runs_agentr_executi_1ed1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['trigger_kind', 'trigger_ref', 'started_at'], name='runs_agentr_trigger_2a436a_idx'),
        ),
    ]
