# Generated by Django 6.0.2 on 2026-03-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0010_agentrun_delivery_target_agentrun_execution_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='approval_fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='approval_mode',
            field=models.CharField(blank=True, choices=[('', 'None'), ('requested', 'Requested'), ('manual', 'Manual'), ('inherited', 'Inherited')], db_index=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='approval_source_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
