# Generated by Django 4.2.28 on 2026-02-23 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDefinition',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('args_schema', models.JSONField(blank=True, default=dict)),
                ('default_risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('ELEVATED', 'Elevated'), ('DANGEROUS', 'Dangerous')], default='SAFE', max_length=12)),
                ('default_requires_approval', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_definitions', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'name'], name='tools_toold_workspa_12035c_idx'), models.Index(fields=['workspace', 'enabled'], name='tools_toold_workspa_7fb803_idx')],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=80)),
                ('args', models.JSONField(blank=True, default=dict)),
                ('risk_level', models.CharField(choices=[('SAFE', 'Safe'), ('ELEVATED', 'Elevated'), ('DANGEROUS', 'Dangerous')], default='SAFE', max_length=12)),
                ('requires_approval', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], db_index=True, default='PENDING', max_length=12)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_tool_calls', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='runs.agentrun')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='runs.agentstep')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'status', 'created_at'], name='tools_toolc_run_id_854389_idx'), models.Index(fields=['tool_name', 'created_at'], name='tools_toolc_tool_na_a0b0ac_idx'), models.Index(fields=['run', 'observed_at'], name='tools_toolc_run_id_91dbb2_idx')],
            },
        ),
    ]
