# Generated by Django 4.2.28 on 2026-02-24 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolcall",
            name="correlation_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
