# Generated by Django 6.0.2 on 2026-03-02 10:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_tooldefinition_workspace_tool_and_agentgrant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenttoolgrant',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tooldefinition',
            name='tools_toold_workspa_12035c_idx',
        ),
        migrations.RemoveIndex(
            model_name='tooldefinition',
            name='tools_tooldefinition_workspace_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='agenttoolgrant',
            new_name='tools_agent_agent_i_b1a98d_idx',
            old_name='tools_agenttoolgrant_agent_tool_idx',
        ),
        migrations.RenameIndex(
            model_name='tooldefinition',
            new_name='tools_toold_workspa_a82869_idx',
            old_name='tools_tooldefinition_workspace_tool_idx',
        ),
        migrations.AddField(
            model_name='toolcall',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='toolcall',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='toolcall',
            name='provider_call_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='toolcall',
            name='provider_response_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='agenttoolgrant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toolcall',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('DENIED', 'Denied'), ('PENDING_APPROVAL', 'Pending Approval'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='REQUESTED', max_length=16),
        ),
        migrations.AlterField(
            model_name='tooldefinition',
            name='name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
