# Generated by Django 6.0.2 on 2026-03-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_toolapprovalgrant_and_toolcall_approval_metadata'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='toolapprovalgrant',
            new_name='tools_toola_run_id_ccf71c_idx',
            old_name='tools_toola_run_id_97a44f_idx',
        ),
        migrations.RenameIndex(
            model_name='toolapprovalgrant',
            new_name='tools_toola_workspa_5469b8_idx',
            old_name='tools_toola_workspa_79c499_idx',
        ),
    ]
