# Generated by Django 4.2.28 on 2026-03-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0007_rename_tools_toola_run_id_97a44f_idx_tools_toola_run_id_ccf71c_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolcall",
            name="exit_code",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
