# Generated by Django 6.0.2 on 2026-02-28 15:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("comms_mirror", "Comms Mirror"),
                            ("internal_only", "Internal Only"),
                            ("run_thread", "Run Thread"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ControlMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Incoming"), ("out", "Outgoing"), ("system", "System")],
                        max_length=16,
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[
                            ("operator", "Operator"),
                            ("agent", "Agent"),
                            ("transport_user", "Transport User"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("author_label", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("source_transport", models.CharField(blank=True, max_length=64, null=True)),
                ("source_conversation_id", models.CharField(blank=True, max_length=128, null=True)),
                ("source_message_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="control.controlconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("transport", models.CharField(max_length=64)),
                ("external_event_id", models.CharField(max_length=255)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-received_at"],
                "unique_together": {("transport", "external_event_id")},
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(blank=True, related_name="operators", to="control.role"),
                ),
            ],
        ),
    ]
