# Generated by Django 6.0.2 on 2026-03-31 23:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_useractionlog"),
        ("finance", "0002_watchlistitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchwabOAuthCredential",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("token_payload_encrypted", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("token_type", models.CharField(blank=True, default="", max_length=64)),
                ("scope", models.CharField(blank=True, default="", max_length=255)),
                ("primary_account_hash", models.CharField(blank=True, default="", max_length=255)),
                ("account_hashes", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RenameIndex(
            model_name="financedatacacheentry",
            new_name="finance_fin_cache_k_345067_idx",
            old_name="finance_cache_cache_key_idx",
        ),
        migrations.RenameIndex(
            model_name="financedatacacheentry",
            new_name="finance_fin_data_ki_1193b7_idx",
            old_name="finance_cache_kind_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="financedatacacheentry",
            new_name="finance_fin_ticker__453c4d_idx",
            old_name="finance_cache_ticker_kind_tf_idx",
        ),
        migrations.RenameIndex(
            model_name="financedatacacheentry",
            new_name="finance_fin_workspa_012384_idx",
            old_name="finance_cache_workspace_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="financeresearchsnapshot",
            new_name="finance_fin_snapsho_e456a5_idx",
            old_name="finance_snapshot_key_idx",
        ),
        migrations.RenameIndex(
            model_name="financeresearchsnapshot",
            new_name="finance_fin_workspa_9e2f50_idx",
            old_name="finance_snapshot_workspace_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="financeresearchsnapshot",
            new_name="finance_fin_ticker__30327b_idx",
            old_name="finance_snapshot_ticker_kind_tf_idx",
        ),
        migrations.RenameIndex(
            model_name="financeresearchsnapshot",
            new_name="finance_fin_portfol_bcd508_idx",
            old_name="finance_snapshot_portfolio_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="financeresearchsnapshot",
            new_name="finance_fin_watchli_dc5b73_idx",
            old_name="finance_snapshot_watchlist_kind_idx",
        ),
        migrations.RenameIndex(
            model_name="portfolio",
            new_name="finance_por_workspa_b9b79c_idx",
            old_name="finance_portfolio_workspace_default_idx",
        ),
        migrations.RenameIndex(
            model_name="portfolio",
            new_name="finance_por_owner_i_5e6455_idx",
            old_name="finance_portfolio_owner_created_idx",
        ),
        migrations.RenameIndex(
            model_name="position",
            new_name="finance_pos_portfol_4e50bf_idx",
            old_name="finance_position_portfolio_ticker_idx",
        ),
        migrations.RenameIndex(
            model_name="position",
            new_name="finance_pos_ticker__1be391_idx",
            old_name="finance_position_ticker_side_idx",
        ),
        migrations.RenameIndex(
            model_name="ticker",
            new_name="finance_tic_symbol_20adef_idx",
            old_name="finance_ticker_symbol_idx",
        ),
        migrations.RenameIndex(
            model_name="ticker",
            new_name="finance_tic_exchang_73b470_idx",
            old_name="finance_ticker_exchange_asset_idx",
        ),
        migrations.RenameIndex(
            model_name="watchlist",
            new_name="finance_wat_workspa_12bd61_idx",
            old_name="finance_watchlist_workspace_default_idx",
        ),
        migrations.RenameIndex(
            model_name="watchlist",
            new_name="finance_wat_owner_i_9c3f23_idx",
            old_name="finance_watchlist_owner_created_idx",
        ),
        migrations.RenameIndex(
            model_name="watchlistitem",
            new_name="finance_wat_watchli_7bf876_idx",
            old_name="finance_watchlist_item_watchlist_created_idx",
        ),
        migrations.RenameIndex(
            model_name="watchlistitem",
            new_name="finance_wat_ticker__d183aa_idx",
            old_name="finance_watchlist_item_ticker_created_idx",
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="watchlistitem",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="schwaboauthcredential",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schwab_credentials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schwaboauthcredential",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schwab_credentials",
                to="core.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="schwaboauthcredential",
            index=models.Index(
                fields=["is_active", "expires_at"], name="finance_sch_is_acti_9e8942_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schwaboauthcredential",
            index=models.Index(
                fields=["workspace", "is_active"], name="finance_sch_workspa_0a04ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schwaboauthcredential",
            index=models.Index(
                fields=["owner", "is_active"], name="finance_sch_owner_i_0d2ec4_idx"
            ),
        ),
    ]
