# Generated by Django 6.0.2 on 2026-04-07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_schwaboauthcredential_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TickerUniverseEntry",
            fields=[
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("symbol", models.CharField(max_length=24, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=180)),
                ("exchange", models.CharField(blank=True, default="", max_length=64)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("EQUITY", "Equity"),
                            ("ETF", "ETF"),
                            ("INDEX", "Index"),
                            ("OPTION", "Option"),
                            ("FUND", "Fund"),
                            ("CRYPTO", "Crypto"),
                            ("OTHER", "Other"),
                        ],
                        default="EQUITY",
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=8)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("source_name", models.CharField(blank=True, default="", max_length=64)),
                ("last_seen_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("source_payload", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddIndex(
            model_name="tickeruniverseentry",
            index=models.Index(fields=["symbol"], name="finance_tic_symbol_6e7c3f_idx"),
        ),
        migrations.AddIndex(
            model_name="tickeruniverseentry",
            index=models.Index(fields=["name"], name="finance_tic_name_6f1f40_idx"),
        ),
        migrations.AddIndex(
            model_name="tickeruniverseentry",
            index=models.Index(fields=["exchange", "asset_type"], name="finance_tic_exchang_3e8b48_idx"),
        ),
        migrations.AddIndex(
            model_name="tickeruniverseentry",
            index=models.Index(fields=["source_name", "is_active"], name="finance_tic_source__e7f4be_idx"),
        ),
    ]
