"""
Django settings for agentmaestro project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import dj_database_url

from core.utils.redis_checks import validate_redis_db

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',  # daphne must be listed before django.contrib.staticfiles
    'django.contrib.staticfiles',

    # Third-party
    'channels',
    'rest_framework',

    # Local apps
    'core',
    'agents',
    'runs',
    'tools',
    'ui',
    'api',
    'llm',
    'control',
    'comms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agentmaestro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agentmaestro.wsgi.application'

ASGI_APPLICATION = 'agentmaestro.asgi.application'

CHANNEL_LAYER_REDIS_URL = os.getenv("CHANNEL_LAYER_REDIS_URL", "redis://127.0.0.1:6379/1")
validate_redis_db(CHANNEL_LAYER_REDIS_URL, 1, "CHANNEL_LAYER_REDIS_URL")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [CHANNEL_LAYER_REDIS_URL]},
    }
}

# Typically the same as the Celery layer
# db0 --> Celery + tool result bus
# db1 --> Django Channels/WS layer
# This separation is good practice, but I make the Tool Bus definition distinct from the Celery Broker db
REDIS_TOOL_BUS_URL = os.getenv(
    "REDIS_TOOL_BUS_URL",
    "redis://127.0.0.1:6379/0",
)
validate_redis_db(REDIS_TOOL_BUS_URL, 0, "REDIS_TOOL_BUS_URL")

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://agentmaestro:agentmaestro@localhost:5432/agentmaestro'
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
validate_redis_db(CELERY_BROKER_URL, 0, "CELERY_BROKER_URL")
BROKER_URL = CELERY_BROKER_URL

ARCHIVE_RETENTION_DAYS = int(os.getenv("ARCHIVE_RETENTION_DAYS", "30"))
ARCHIVE_INTERVAL_HOURS = int(os.getenv("ARCHIVE_INTERVAL_HOURS", "6"))
ARCHIVE_LIMIT = int(os.getenv("ARCHIVE_LIMIT", "25"))
ARCHIVE_COMPACT_EVENTS = os.getenv("ARCHIVE_COMPACT_EVENTS", "true").lower() in {
    "1",
    "true",
    "yes",
}

RECONCILE_INTERVAL = int(os.getenv("RECONCILE_INTERVAL", "30"))

TELEGRAM_POLL_INTERVAL_SECONDS = int(os.getenv("TELEGRAM_POLL_INTERVAL_SECONDS", "5"))
TELEGRAM_POLL_TIMEOUT_SECONDS = int(os.getenv("TELEGRAM_POLL_TIMEOUT_SECONDS", "25"))
TELEGRAM_POLL_LOCK_TIMEOUT_SECONDS = int(os.getenv("TELEGRAM_POLL_LOCK_TIMEOUT_SECONDS", "30"))
TELEGRAM_POLL_LOCK_REDIS_URL = (
    os.getenv("TELEGRAM_POLL_LOCK_REDIS_URL")
    or os.getenv("CHANNEL_LAYER_REDIS_URL")
    or os.getenv("CELERY_BROKER_URL")
)

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID", "")

OPENAI_MODELS_REFRESH_INTERVAL_HOURS = int(os.getenv("OPENAI_MODELS_REFRESH_INTERVAL_HOURS", "24"))

CELERY_BEAT_SCHEDULE = {
    "runs.reconcile_waiting_subruns": {
        "task": "runs.tasks.reconcile_waiting_subruns",
        "schedule": timedelta(seconds=RECONCILE_INTERVAL),
    },
    "runs.archive_completed_runs": {
        "task": "runs.tasks.archive_completed_runs",
        "schedule": timedelta(hours=ARCHIVE_INTERVAL_HOURS),
    },
    #"llm.refresh_openai_models": {
    #    "task": "llm.tasks.refresh_openai_models",
    #    "schedule": timedelta(hours=OPENAI_MODELS_REFRESH_INTERVAL_HOURS),
    #},  TODO add back in periodic model refreshes
    #"comms.telegram_poll_scheduler": {
    #    "task": "comms.tasks.telegram_poll_scheduler",
    #    "schedule": timedelta(seconds=TELEGRAM_POLL_INTERVAL_SECONDS),
    #},  TODO add back in telegram poll scheduler
}

# ToolRunner settings (new preferred names)
TOOLRUNNER_BASE_URL = os.getenv("TOOLRUNNER_BASE_URL")
if TOOLRUNNER_BASE_URL:
    TOOLRUNNER_URL = f"{TOOLRUNNER_BASE_URL.rstrip('/')}/v1/run/tool"
else:
    TOOLRUNNER_URL = os.getenv("TOOLRUNNER_URL") or "http://127.0.0.1:8001/v1/run/tool"

TOOLRUNNER_SECRET = os.getenv("TOOLRUNNER_SECRET") or "insecure-secret"
TOOLRUNNER_TIMEOUT = int(os.getenv("TOOLRUNNER_TIMEOUT", "30"))
TOOLRUNNER_OUTPUT_LIMIT = int(os.getenv("TOOLRUNNER_OUTPUT_LIMIT", "4096"))
TOOLRUNNER_HTTP_TIMEOUT = int(os.getenv("TOOLRUNNER_HTTP_TIMEOUT", "45"))

# LLM defaults
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openai")
LLM_DEFAULT_PROFILE_PLANNER = os.getenv("LLM_DEFAULT_PROFILE_PLANNER", "Maestro")
LLM_DEFAULT_PROFILE_CODER = os.getenv("LLM_DEFAULT_PROFILE_CODER", "Apprentice")
LLM_TIMEOUT_SECONDS = int(os.getenv("LLM_TIMEOUT_SECONDS", "60"))
LLM_MAX_RETRIES = int(os.getenv("LLM_MAX_RETRIES", "3"))

# OPENAI KEY
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_WS_DEBUG = os.getenv("OPENAI_WS_DEBUG", "0")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com")
OPENAI_TRANSPORT = os.getenv("OPENAI_TRANSPORT", "http")
OPENAI_WS_TIMEOUT_SECONDS = os.getenv("OPENAI_WS_TIMEOUT_SECONDS", "120")
OPENAI_WS_IDLE_TIMEOUT_SECONDS = os.getenv("OPENAI_WS_IDLE_TIMEOUT_SECONDS", "1200")
OPENAI_HTTP_MODE = os.getenv("OPENAI_HTTP_MODE", "responses")

SCRUB_PROMPTS = os.getenv("SCRUB_PROMPTS", "1") != "0"
SCRUB_PROMPTS_FOR_TESTS = os.getenv("SCRUB_PROMPTS_FOR_TESTS", "0") != "0"
TESTING = False

TOOLRUNNER_TOOL_CALL_RESULT_TIMEOUT_SECONDS = os.getenv("TOOLRUNNER_TOOL_CALL_RESULT_TIMEOUT_SECONDS", 30)
