"""
Django settings for agentmaestro project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import ast
import json
from datetime import timedelta
from pathlib import Path
import os
import dj_database_url
from kombu import Queue

from core.utils.redis_checks import validate_redis_db

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

_ENV_PATH = BASE_DIR / ".env"


def _load_env_file() -> dict[str, str]:
    if not _ENV_PATH.exists():
        return {}
    data: dict[str, str] = {}
    for line in _ENV_PATH.read_text(encoding="utf-8").splitlines():
        maybe = line.split("#", 1)[0].strip()
        if not maybe or "=" not in maybe:
            continue
        key, _, value = maybe.partition("=")
        data[key.strip()] = value.strip()
    return data


_ENV_FILE_VALUES = _load_env_file()


def _env_value(key: str, default: str = "") -> str:
    explicit = os.getenv(key)
    if explicit is not None:
        return explicit
    return _ENV_FILE_VALUES.get(key, default)


def _env_json_list(key: str, default: list[str] | None = None) -> list[str]:
    raw = _env_value(key, "")
    if not raw:
        return list(default or [])
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        try:
            parsed = ast.literal_eval(raw)
        except (ValueError, SyntaxError):
            return [item.strip() for item in raw.split(",") if item.strip()]
    if isinstance(parsed, list):
        return [str(item).strip() for item in parsed if str(item).strip()]
    return list(default or [])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'dev-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'daphne',  # daphne must be listed before django.contrib.staticfiles
    'django.contrib.staticfiles',

    # Third-party
    'channels',
    'rest_framework',

    # Local apps
    'core',
    'agents',
    'runs',
    'memory',
    'tools',
    'ui',
    'api',
    'llm',
    'control',
    'comms',
    'google_bridge',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'agentmaestro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'agentmaestro.wsgi.application'

ASGI_APPLICATION = 'agentmaestro.asgi.application'

CHANNEL_LAYER_REDIS_URL = os.getenv("CHANNEL_LAYER_REDIS_URL", "redis://127.0.0.1:6379/1")
validate_redis_db(CHANNEL_LAYER_REDIS_URL, 1, "CHANNEL_LAYER_REDIS_URL")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [CHANNEL_LAYER_REDIS_URL]},
    }
}

# Typically the same as the Celery layer
# db0 --> Celery + tool result bus
# db1 --> Django Channels/WS layer
# This separation is good practice, but I make the Tool Bus definition distinct from the Celery Broker db
REDIS_TOOL_BUS_URL = os.getenv(
    "REDIS_TOOL_BUS_URL",
    "redis://127.0.0.1:6379/0",
)
validate_redis_db(REDIS_TOOL_BUS_URL, 0, "REDIS_TOOL_BUS_URL")

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://agentmaestro:agentmaestro@localhost:5432/agentmaestro'
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Canonical local timezone for the app and agent prompt.
# Use an IANA timezone name such as "America/New_York", not a UTC offset.
LOCAL_TIME_ZONE = _env_value("TIME_ZONE") or _env_value("TANGO_TIME_ZONE") or "America/New_York"
TIME_ZONE = LOCAL_TIME_ZONE
TANGO_TIME_ZONE = LOCAL_TIME_ZONE

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
validate_redis_db(CELERY_BROKER_URL, 0, "CELERY_BROKER_URL")
BROKER_URL = CELERY_BROKER_URL
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_QUEUES = (
    Queue("celery"),
    Queue("tools"),
    Queue("runs"),
    Queue("comms"),
)
CELERY_TASK_ROUTES = {
    "tools.execute_tool_call_async": {"queue": "tools"},
    "runs.tasks.reconcile_waiting_subruns": {"queue": "runs"},
    "runs.tasks.archive_completed_runs": {"queue": "runs"},
    "runs.tasks.purge_consumed_artifacts": {"queue": "runs"},
    "runs.tasks.execute_headless_run": {"queue": "runs"},
    "comms.tasks.telegram_poll_scheduler": {"queue": "comms"},
    "comms.tasks.telegram_poll_once": {"queue": "comms"},
    "comms.tasks.expire_remote_approval_tickets_task": {"queue": "comms"},
    "memory.tasks.run_due_scheduled_tasks": {"queue": "runs"},
    "memory.tasks.run_scheduled_task_once": {"queue": "runs"},
    "memory.tasks.run_memory_retention_task": {"queue": "runs"},
}

ARCHIVE_RETENTION_DAYS = int(os.getenv("ARCHIVE_RETENTION_DAYS", "30"))
ARCHIVE_INTERVAL_HOURS = int(os.getenv("ARCHIVE_INTERVAL_HOURS", "6"))
ARCHIVE_LIMIT = int(os.getenv("ARCHIVE_LIMIT", "25"))
ARCHIVE_COMPACT_EVENTS = os.getenv("ARCHIVE_COMPACT_EVENTS", "true").lower() in {
    "1",
    "true",
    "yes",
}
ARTIFACT_RETENTION_DAYS = int(os.getenv("ARTIFACT_RETENTION_DAYS", "30"))
ARTIFACT_PURGE_INTERVAL_HOURS = int(os.getenv("ARTIFACT_PURGE_INTERVAL_HOURS", "24"))
ARTIFACT_PURGE_LIMIT = int(os.getenv("ARTIFACT_PURGE_LIMIT", "500"))

RECONCILE_INTERVAL = int(os.getenv("RECONCILE_INTERVAL", "30"))
# Tool-call concurrency is intentionally configured via the toolrunner-prefixed env var
# so the worker-side limit is obvious in deployment configs. The approval flow no
# longer enforces a per-run gate, but we keep this setting for compatibility.
MAX_CONCURRENT_TOOL_CALLS_PER_RUN = int(_env_value("TOOLRUNNER_MAX_CONCURRENT_TOOL_CALLS_PER_RUN") or "6")
# Gmail OR clauses are capped to keep fan-out bounded. The bridge rejects nested OR
# inside parentheses instead of guessing the user's intent.
GMAIL_OR_CLAUSE_LIMIT = int(_env_value("TOOLRUNNER_GMAIL_OR_CLAUSE_LIMIT") or "10")

TELEGRAM_ENABLE_POLLING = (_env_value("TELEGRAM_ENABLE_POLLING") or "0").lower() in {
    "1",
    "true",
    "yes",
}
TELEGRAM_POLL_INTERVAL_SECONDS = int(_env_value("TELEGRAM_POLL_INTERVAL_SECONDS") or "5")
TELEGRAM_POLL_TIMEOUT_SECONDS = max(1, int(_env_value("TELEGRAM_POLL_TIMEOUT_SECONDS") or "5"))
TELEGRAM_POLL_TIMEOUT_RETRIES = int(_env_value("TELEGRAM_POLL_TIMEOUT_RETRIES") or "1")
TELEGRAM_POLL_LOCK_TIMEOUT_SECONDS = int(_env_value("TELEGRAM_POLL_LOCK_TIMEOUT_SECONDS") or "30")
TELEGRAM_POLL_LOCK_REDIS_URL = (
    _env_value("TELEGRAM_POLL_LOCK_REDIS_URL")
    or _env_value("CHANNEL_LAYER_REDIS_URL")
    or _env_value("CELERY_BROKER_URL")
)

TELEGRAM_BOT_TOKEN = _env_value("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = _env_value("TELEGRAM_CHAT_ID")
REMOTE_APPROVAL_TTL_MINUTES = int(_env_value("REMOTE_APPROVAL_TTL_MINUTES") or "15")
REMOTE_APPROVAL_EXPIRY_INTERVAL_SECONDS = int(_env_value("REMOTE_APPROVAL_EXPIRY_INTERVAL_SECONDS") or "60")
SCHEDULED_TASK_INTERVAL_SECONDS = int(_env_value("SCHEDULED_TASK_INTERVAL_SECONDS") or "60")
SCHEDULED_TASK_BATCH_LIMIT = int(_env_value("SCHEDULED_TASK_BATCH_LIMIT") or "10")
HEADLESS_RUN_STALE_TIMEOUT_MINUTES = int(_env_value("HEADLESS_RUN_STALE_TIMEOUT_MINUTES") or "30")
SCHEDULED_HEADLESS_APPROVAL_TTL_DAYS = int(_env_value("SCHEDULED_HEADLESS_APPROVAL_TTL_DAYS") or "30")

GOOGLE_CLIENT_ID = _env_value("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = _env_value("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = _env_value("GOOGLE_REDIRECT_URI")
GOOGLE_OAUTH_SCOPES = _env_json_list(
    "GOOGLE_OAUTH_SCOPES",
    [
        "openid",
        "email",
        "profile",
        "https://www.googleapis.com/auth/gmail.readonly",
        "https://www.googleapis.com/auth/gmail.modify",
        "https://www.googleapis.com/auth/calendar.readonly",
        "https://www.googleapis.com/auth/calendar",
    ],
)

MEMORY_RETENTION_ENABLED = (_env_value("MEMORY_RETENTION_ENABLED") or "0").lower() in {"1", "true", "yes"}
MEMORY_RETENTION_DAYS = int(_env_value("MEMORY_RETENTION_DAYS") or "30")
MEMORY_RETENTION_BATCH_SIZE = int(_env_value("MEMORY_RETENTION_BATCH_SIZE") or "500")
MEMORY_EPISODIC_DISTILL_GROUP_LIMIT = int(_env_value("MEMORY_EPISODIC_DISTILL_GROUP_LIMIT") or "50")
MEMORY_RETENTION_INTERVAL_HOURS = int(_env_value("MEMORY_RETENTION_INTERVAL_HOURS") or "24")
MEMORY_RETENTION_LOW_IMPORTANCE_THRESHOLD = _env_value("MEMORY_RETENTION_LOW_IMPORTANCE_THRESHOLD") or "0.40"
MEMORY_RETENTION_PROTECTED_IMPORTANCE_THRESHOLD = _env_value("MEMORY_RETENTION_PROTECTED_IMPORTANCE_THRESHOLD") or "0.80"

AGENTMAESTRO_BASE_URL = (_env_value("AGENTMAESTRO_BASE_URL") or "http://127.0.0.1:8000").rstrip("/")
OPENAI_MODELS_REFRESH_INTERVAL_HOURS = int(os.getenv("OPENAI_MODELS_REFRESH_INTERVAL_HOURS", "24"))

CELERY_BEAT_SCHEDULE = {
    "runs.reconcile_waiting_subruns": {
        "task": "runs.tasks.reconcile_waiting_subruns",
        "schedule": timedelta(seconds=RECONCILE_INTERVAL),
        "options": {"expires": max(RECONCILE_INTERVAL, 30)},
    },
    "runs.archive_completed_runs": {
        "task": "runs.tasks.archive_completed_runs",
        "schedule": timedelta(hours=ARCHIVE_INTERVAL_HOURS),
    },
    "runs.purge_consumed_artifacts": {
        "task": "runs.tasks.purge_consumed_artifacts",
        "schedule": timedelta(hours=ARTIFACT_PURGE_INTERVAL_HOURS),
        "options": {"expires": max(ARTIFACT_PURGE_INTERVAL_HOURS * 3600, 300)},
    },
    #"llm.refresh_openai_models": {
    #    "task": "llm.tasks.refresh_openai_models",
    #    "schedule": timedelta(hours=OPENAI_MODELS_REFRESH_INTERVAL_HOURS),
    #},  TODO add back in periodic model refreshes
    "comms.expire_remote_approval_tickets": {
        "task": "comms.tasks.expire_remote_approval_tickets_task",
        "schedule": timedelta(seconds=REMOTE_APPROVAL_EXPIRY_INTERVAL_SECONDS),
        "options": {"expires": max(REMOTE_APPROVAL_EXPIRY_INTERVAL_SECONDS, 30)},
    },
    "memory.run_due_scheduled_tasks": {
        "task": "memory.tasks.run_due_scheduled_tasks",
        "schedule": timedelta(seconds=SCHEDULED_TASK_INTERVAL_SECONDS),
        "options": {"expires": max(SCHEDULED_TASK_INTERVAL_SECONDS, 30)},
    },
}

if TELEGRAM_ENABLE_POLLING:
    CELERY_BEAT_SCHEDULE["comms.telegram_poll_scheduler"] = {
        "task": "comms.tasks.telegram_poll_scheduler",
        "schedule": timedelta(seconds=TELEGRAM_POLL_INTERVAL_SECONDS),
        "options": {"expires": max(TELEGRAM_POLL_INTERVAL_SECONDS * 2, 15)},
    }

if MEMORY_RETENTION_ENABLED:
    CELERY_BEAT_SCHEDULE["memory.run_memory_retention"] = {
        "task": "memory.tasks.run_memory_retention_task",
        "schedule": timedelta(hours=MEMORY_RETENTION_INTERVAL_HOURS),
        "options": {"expires": max(MEMORY_RETENTION_INTERVAL_HOURS * 3600, 300)},
    }

# ToolRunner settings (new preferred names)
TOOLRUNNER_SANDBOX_ROOT = _env_value("TOOLRUNNER_SANDBOX_ROOT", "/tmp/agentmaestro/sandbox")
TOOLRUNNER_BASE_URL = _env_value("TOOLRUNNER_BASE_URL")
if TOOLRUNNER_BASE_URL:
    TOOLRUNNER_URL = f"{TOOLRUNNER_BASE_URL.rstrip('/')}/v1/run/tool"
else:
    TOOLRUNNER_URL = _env_value("TOOLRUNNER_URL") or "http://127.0.0.1:8001/v1/run/tool"

TOOLRUNNER_SECRET = _env_value("TOOLRUNNER_SECRET") or "insecure-secret"
TOOLRUNNER_TIMEOUT = int(_env_value("TOOLRUNNER_TIMEOUT") or "30")
TOOLRUNNER_OUTPUT_LIMIT = int(_env_value("TOOLRUNNER_OUTPUT_LIMIT") or "4096")
TOOLRUNNER_HTTP_TIMEOUT = int(_env_value("TOOLRUNNER_HTTP_TIMEOUT") or "45")

# LLM defaults
LLM_PROVIDER = os.getenv("LLM_PROVIDER", "openai")
LLM_DEFAULT_PROFILE_PLANNER = os.getenv("LLM_DEFAULT_PROFILE_PLANNER", "Maestro")
LLM_DEFAULT_PROFILE_CODER = os.getenv("LLM_DEFAULT_PROFILE_CODER", "Apprentice")
LLM_TIMEOUT_SECONDS = int(os.getenv("LLM_TIMEOUT_SECONDS", "60"))
LLM_MAX_RETRIES = int(os.getenv("LLM_MAX_RETRIES", "3"))
HEADLESS_RUN_MAX_TOOL_ROUNDS = int(os.getenv("HEADLESS_RUN_MAX_TOOL_ROUNDS", "4"))
HEADLESS_RUN_MAX_DURATION_SECONDS = int(os.getenv("HEADLESS_RUN_MAX_DURATION_SECONDS", "1800"))

# OPENAI KEY
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_WS_DEBUG = os.getenv("OPENAI_WS_DEBUG", "0")
OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL", "https://api.openai.com")
OPENAI_TRANSPORT = _env_value("OPENAI_TRANSPORT", "ws")
OPENAI_WS_TIMEOUT_SECONDS = os.getenv("OPENAI_WS_TIMEOUT_SECONDS", "120")
OPENAI_WS_IDLE_TIMEOUT_SECONDS = os.getenv("OPENAI_WS_IDLE_TIMEOUT_SECONDS", "1200")
OPENAI_WS_MAX_RETRIES = int(_env_value("OPENAI_WS_MAX_RETRIES") or "3")
OPENAI_WS_MAX_RETRY_JITTER_MS = int(_env_value("OPENAI_WS_MAX_RETRY_JITTER_MS") or "250")
OPENAI_HTTP_MODE = os.getenv("OPENAI_HTTP_MODE", "responses")

# GEMINI KEY
GEMINI_API_KEY = _env_value("GEMINI_API_KEY", "")
GEMINI_BASE_URL = _env_value("GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta")
GEMINI_TRANSPORT = _env_value("GEMINI_TRANSPORT", "http")
GEMINI_HTTP_MODE = _env_value("GEMINI_HTTP_MODE", "responses")
SHOW_CONDENSED_SYSTEM_LOGS = os.getenv("SHOW_CONDENSED_SYSTEM_LOGS", "1") != "0"

SCRUB_PROMPTS = os.getenv("SCRUB_PROMPTS", "1") != "0"
SCRUB_PROMPTS_FOR_TESTS = os.getenv("SCRUB_PROMPTS_FOR_TESTS", "0") != "0"
TESTING = False

TOOLRUNNER_TOOL_CALL_RESULT_TIMEOUT_SECONDS = os.getenv("TOOLRUNNER_TOOL_CALL_RESULT_TIMEOUT_SECONDS", 30)
