# Generated by Django 6.0.2 on 2026-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0002_llmrun_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodelprofile",
            name="agent_role",
            field=models.CharField(
                choices=[
                    ("planner", "Planner"),
                    ("coder", "Coder"),
                    ("assistant", "Assistant"),
                    ("researcher", "Researcher"),
                    ("writer", "Writer"),
                    ("generic", "Generic"),
                ],
                default="generic",
                max_length=20,
            ),
        ),
    ]
