# Generated by Django 6.0.2 on 2026-03-04 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llm", "0003_alter_llmmodelprofile_agent_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelsAvailable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("company", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("api", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("company", "api", "name"),
                "unique_together": {("company", "api", "name")},
            },
        ),
    ]
