# Generated by Django 6.0.2 on 2026-03-13 17:26

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scope_type', models.CharField(choices=[('sandbox', 'Sandbox'), ('agent', 'Agent'), ('user', 'User')], max_length=24)),
                ('scope_id', models.CharField(db_index=True, max_length=128)),
                ('memory_kind', models.CharField(choices=[('semantic', 'Semantic'), ('procedural', 'Procedural')], max_length=24)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('importance', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3)),
                ('last_accessed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope_type', 'scope_id', 'memory_kind'], name='memory_memo_scope_t_baeb32_idx'), models.Index(fields=['scope_type', 'scope_id', 'updated_at'], name='memory_memo_scope_t_a03576_idx'), models.Index(fields=['memory_kind', 'updated_at'], name='memory_memo_memory__5ef9d8_idx')],
            },
        ),
    ]
