# Generated by Django 6.0.2 on 2026-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryrecord",
            name="memory_kind",
            field=models.CharField(
                choices=[
                    ("episodic", "Episodic"),
                    ("semantic", "Semantic"),
                    ("procedural", "Procedural"),
                ],
                max_length=24,
            ),
        ),
    ]
