# Generated by Django 6.0.2 on 2026-03-13 22:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agent_default_model'),
        ('core', '0002_useractionlog'),
        ('memory', '0002_alter_memoryrecord_memory_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=160)),
                ('task_type', models.CharField(choices=[('daily_weather_report', 'Daily Weather Report')], max_length=48)),
                ('schedule_kind', models.CharField(choices=[('daily_time', 'Daily Time')], default='daily_time', max_length=24)),
                ('delivery_target', models.CharField(choices=[('paired_transport', 'Paired Transport')], default='paired_transport', max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('local_time', models.TimeField()),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('last_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('execution_payload', models.JSONField(blank=True, default=dict)),
                ('last_result_summary', models.TextField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_tasks', to='agents.agent')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_tasks', to=settings.AUTH_USER_MODEL)),
                ('source_memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='memory.memoryrecord')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['enabled', 'next_run_at'], name='memory_sche_enabled_5054a3_idx'), models.Index(fields=['agent', 'enabled', 'next_run_at'], name='memory_sche_agent_i_40b607_idx'), models.Index(fields=['workspace', 'enabled', 'next_run_at'], name='memory_sche_workspa_351b54_idx'), models.Index(fields=['task_type', 'enabled', 'next_run_at'], name='memory_sche_task_ty_c8a5ea_idx')],
            },
        ),
    ]
