# Generated by Django 6.0.2 on 2026-03-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_scheduledtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryrecord',
            name='access_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memoryrecord',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryrecord',
            name='pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('daily_weather_report', 'Daily Weather Report'), ('daily_email_check', 'Daily Email Check'), ('other_daily_task', 'Other Daily Task')], max_length=48),
        ),
    ]
