# Generated by Django 6.0.2 on 2026-03-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_memoryrecord_access_count_memoryrecord_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryrecord',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='memoryrecord',
            name='source_kind',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='memoryrecord',
            name='source_ref',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='memoryrecord',
            index=models.Index(fields=['scope_type', 'scope_id', 'memory_kind', 'dedupe_key'], name='memory_memo_scope_t_8b07a9_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryrecord',
            index=models.Index(fields=['source_kind', 'updated_at'], name='memory_memo_source__e9b7a5_idx'),
        ),
    ]
