# Generated by Django 6.0.2 on 2026-03-15 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_memoryrecord_dedupe_key_memoryrecord_source_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryHealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('compare_days', models.PositiveIntegerField(default=30)),
                ('total_records', models.PositiveIntegerField(db_index=True, default=0)),
                ('pinned_records', models.PositiveIntegerField(default=0)),
                ('high_importance_records', models.PositiveIntegerField(default=0)),
                ('retention_candidate_records', models.PositiveIntegerField(default=0)),
                ('scheduled_tasks_total', models.PositiveIntegerField(default=0)),
                ('report_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'total_records'], name='memory_memo_created_1a0a2b_idx')],
            },
        ),
    ]
