# Generated by Django 6.0.2 on 2026-03-15 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agent_default_model'),
        ('core', '0002_useractionlog'),
        ('memory', '0006_memoryhealthsnapshot'),
        ('runs', '0009_runmemory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='active_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks_as_active_run', to='runs.agentrun'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='execution_mode',
            field=models.CharField(choices=[('deterministic', 'Deterministic'), ('headless_run', 'Headless Run')], db_index=True, default='deterministic', max_length=24),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='last_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks_as_last_run', to='runs.agentrun'),
        ),
        migrations.AddIndex(
            model_name='scheduledtask',
            index=models.Index(fields=['enabled', 'execution_mode', 'next_run_at'], name='memory_sche_enabled_67949c_idx'),
        ),
    ]
