# Generated by Django 6.0.2 on 2026-03-15 14:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agent_default_model'),
        ('core', '0002_useractionlog'),
        ('memory', '0007_scheduledtask_active_run_and_more'),
        ('runs', '0011_agentrun_approval_fingerprint_agentrun_approval_mode_and_more'),
        ('tools', '0007_rename_tools_toola_run_id_97a44f_idx_tools_toola_run_id_ccf71c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('fingerprint_version', models.PositiveSmallIntegerField(default=1)),
                ('execution_mode', models.CharField(default='headless_run', max_length=24)),
                ('task_type', models.CharField(max_length=48)),
                ('delivery_target', models.CharField(blank=True, default='', max_length=32)),
                ('normalized_execution_payload', models.JSONField(blank=True, default=dict)),
                ('tool_signature', models.JSONField(blank=True, default=list)),
                ('approved_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_task_approvals', to='agents.agent')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_task_approvals', to=settings.AUTH_USER_MODEL)),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='memory.scheduledtask')),
                ('source_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_task_approvals', to='runs.agentrun')),
                ('source_tool_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_task_approvals', to='tools.toolcall')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_task_approvals', to='core.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['scheduled_task', 'fingerprint', 'fingerprint_version'], name='memory_sche_schedul_3b279d_idx'), models.Index(fields=['scheduled_task', 'revoked_at', 'expires_at'], name='memory_sche_schedul_fab613_idx'), models.Index(fields=['agent', 'approved_at'], name='memory_sche_agent_i_1fca82_idx')],
            },
        ),
    ]
