# Generated by Django 6.0.2 on 2026-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0009_recurrencerule_scheduledtask_recurrence_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("daily_weather_report", "Daily Weather Report"),
                    ("daily_email_check", "Daily Email Check"),
                    ("daily_calendar_check", "Daily Calendar Check"),
                    ("other_daily_task", "Other Daily Task"),
                    ("other_task", "Other Task"),
                ],
                max_length=48,
            ),
        ),
    ]
