# Generated by Django 6.0.2 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0010_alter_scheduledtask_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="execution_mode",
            field=models.CharField(
                choices=[("headless_run", "Headless Run")],
                db_index=True,
                default="headless_run",
                max_length=24,
            ),
        ),
    ]
