# Generated by Django 6.0.2 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0011_alter_scheduledtask_execution_mode_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("other_task", "Other Task"),
                ],
                max_length=48,
            ),
        ),
    ]
