# Generated by Django 6.0.2 on 2026-03-20

from django.db import migrations


def forwards(apps, schema_editor):
    ScheduledTask = apps.get_model("memory", "ScheduledTask")
    ScheduledTask.objects.exclude(task_type="other_task").update(task_type="other_task")


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0012_alter_scheduledtask_task_type_choices"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
