# Generated by Django 6.0.2 on 2026-03-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_useractionlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("google_subject", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("email", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("scopes", models.JSONField(blank=True, default=list)),
                ("access_token_ciphertext", models.BinaryField(blank=True, default=b"")),
                ("refresh_token_ciphertext", models.BinaryField(blank=True, default=b"")),
                ("token_expires_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_accounts",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["workspace", "owner", "is_active"], name="gbr_ws_owner_active_idx"),
                    models.Index(fields=["workspace", "google_subject"], name="gbr_ws_subject_idx"),
                    models.Index(fields=["email", "is_active"], name="gbr_email_active_idx"),
                ],
            },
        ),
    ]
